kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        deployment: postgresql
    spec:
      securityContext:
        fsGroup: 0
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
      containers:
        - name: postgresql
          image: "image-registry.openshift-image-registry.svc:5000/openshift/postgresql:15-el9"
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              value: sonar
            - name: POSTGRESQL_PASSWORD
              value: sonar
            - name: POSTGRESQL_DATABASE
              value: sonar
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - "--live"
            initialDelaySeconds: 120
            timeoutSeconds: 10
  strategy:
    type: Recreate
